version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: unless-stopped
    hostname: 'testgitlab.ru'          # Change host here
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://testgitlab.ru'       # Change url here
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }

        # DATABASE CONNECTION SETTINGS: in our case we use postgresql as database
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_database'] = "gitlab"
        gitlab_rails['db_username'] = "postgres"
        gitlab_rails['db_password'] = "03031996" # set the database password here
        gitlab_rails['db_host'] = "gitlab_database"

        # GITLAB DOCKER IMAGE REGISTRY: so that we can use our docker image registry with gitlab
        registry['enable'] = false # we do not activate this option because we provide our own registry
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "registry.testgitlab.ru"                       # Change registry host here
        gitlab_rails['registry_api_url'] = "https://registry.testgitlab.ru"            # Change registry url here
        gitlab_rails['registry_issuer'] = "gitlab-issuer"

        # SMTP SETTINGS: So that gitlab can send emails. In our case we send via google mail.
        #gitlab_rails['smtp_enable'] = true
        #gitlab_rails['smtp_address'] = "smtp.gmail.com"
        #gitlab_rails['smtp_port'] = 587
        #gitlab_rails['smtp_user_name'] = "gitlab@example.com"
        #gitlab_rails['smtp_password'] = "xxxx"
        #gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        #gitlab_rails['smtp_authentication'] = "login"
        #gitlab_rails['smtp_enable_starttls_auto'] = true
        #gitlab_rails['smtp_tls'] = false
        #gitlab_rails['smtp_openssl_verify_mode'] = "peer"


    ports:
      - "2222:22"
    networks:
      - traefik_gitlab_net
      - gitlab_net
    volumes:
      - /srv/docker/volumes/gitlab/config:/etc/gitlab
      - /srv/docker/volumes/gitlab/logs:/var/log/gitlab
      - /srv/docker/volumes/gitlab/data:/var/opt/gitlab
      - /srv/docker/volumes/registry/certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.gitlab.port=80"
      - "traefik.gitlab.backend=gitlab"
      - "traefik.gitlab.frontend.rule=Host:testgitlab.ru"      # Change host here
      - "traefik.gitlab.frontend.entryPoints=http,https"
      - "traefik.docker.network=gitlab_traefik_gitlab_net"

  registry:
    restart: unless-stopped
    image: registry:2.7
    container_name: gitlab_registry
    volumes:
     - /srv/docker/volumes/registry/data:/registry
     - /srv/docker/volumes/registry/certs:/certs
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:registry.testgitlab.ru"      # Change registry host here
    - "traefik.port=5000"
    - "traefik.backend=gitlab-registry"
    - "traefik.frontend.entryPoints=http,https"
    networks:
      - traefik_gitlab_net
    environment:
      REGISTRY_LOG_LEVEL: debug
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
      REGISTRY_AUTH_TOKEN_REALM: https://testgitlab.ru/jwt/auth    # Change url here
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: gitlab-issuer
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/gitlab-registry.crt
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

  database:
    image: postgres:14-alpine
    container_name: gitlab_database
    restart: unless-stopped
    networks:
      - gitlab_net
    environment:
      POSTGRES_PASSWORD: "03031996" # use the same password as the one you used above
      POSTGRES_DB: gitlab
    volumes:
      - /srv/docker/volumes/gitlab/database:/var/lib/postgresql/data

  traefik:
    container_name: gitlab_traefik
    restart: unless-stopped
    image: traefik:v1.7-alpine
    command:
        --configFile=/var/traefik/traefik.toml
    ports:
      - "443:443"
      - "80:80"
      - "8090:8090"
    networks:
      - traefik_gitlab_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/var/traefik/traefik.toml:ro
      - /srv/docker/volumes/traefik/log:/log

networks:
  traefik_gitlab_net:
  gitlab_net:

